# Generated by Django 6.0.1 on 2026-01-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_user_professional_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='email',
            field=models.EmailField(default='teste@teste.com', max_length=254, unique=True),
        ),
    ]
